### PR TITLE
Add a bunch of new functionality

### PR DESCRIPTION
**Pull request by fejta**
* Search for issue opened by anyone, not just Jess ;-)
* Create new issue when previous one was closed without creating the SECURITY_CONTACTS file (`--skip-open=false`)
* Ping open issues on a regular basis (`--bump=7`)
* Auto-assign people  (`--assign-days=10`, `--assignees=5`, `--skip-assignee=k8s-ci-robot`)
* Auto-close issues once there is a SECURITY_CONTACTS file (`--skip-close=false`)
* Add flags to modify behavior:
  - `--org`: control which orgs to scan
  - `--skip-repo`: do not scan this repo
  - `--skip-emails`: do not log email addresses in the file
  - `--confirm`: actually created/edit issues, otherwise pretend.
  - `--token-path`: read token from this file instead of putting the value in `--token`

Require go-github to be on the local path until https://github.com/google/go-github/pull/1076 is addressed

### CODE REVIEW

**Comment by jessfraz** [comment]
can we have either or? like both work because I use the env var :)

**Comment by fejta** [comment]
Sure... Do you mean the path in a var or flag? Or the value in a var or flag? Or all of the above?

Maybe value in env or path in flag?

**Comment by fejta** [comment]
Okay how about this instead? I made the program much more annoying! 😈

**Comment by jessfraz** [comment]
thanks!!! you are the best

**Pull request merged**
